using EventRegistrationApp.EntityFrameworkCore;
using Xunit;

namespace EventRegistrationApp.EntityFrameworkCore;

public class EventRegistrationAppEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<EventRegistrationAppEntityFrameworkCoreFixture>
{

}
